//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDS.WorkflowExtenders.SiteWorkflowService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://sharePoint.workflow", ItemName="string")]
    [System.SerializableAttribute()]
    internal class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteWorkflowInfo", Namespace="http://sharePoint.workflow")]
    [System.SerializableAttribute()]
    internal partial class SiteWorkflowInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkflowTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowParameterInfo> WorkflowParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string WorkflowName {
            get {
                return this.WorkflowNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowNameField, value) != true)) {
                    this.WorkflowNameField = value;
                    this.RaisePropertyChanged("WorkflowName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string WorkflowTitle {
            get {
                return this.WorkflowTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowTitleField, value) != true)) {
                    this.WorkflowTitleField = value;
                    this.RaisePropertyChanged("WorkflowTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        internal System.Collections.Generic.List<MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowParameterInfo> WorkflowParameters {
            get {
                return this.WorkflowParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkflowParametersField, value) != true)) {
                    this.WorkflowParametersField = value;
                    this.RaisePropertyChanged("WorkflowParameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SiteWorkflowParameterInfo", Namespace="http://sharePoint.workflow")]
    [System.SerializableAttribute()]
    internal partial class SiteWorkflowParameterInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        internal string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sharePoint.workflow", ConfigurationName="SiteWorkflowService.SiteWorkflowActivationServiceSoap")]
    internal interface SiteWorkflowActivationServiceSoap {
        
        // CODEGEN: Generating message contract since element name siteUrl from namespace http://sharePoint.workflow is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sharePoint.workflow/StartSiteWorkflow", ReplyAction="*")]
        MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowResponse StartSiteWorkflow(MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequest request);
        
        // CODEGEN: Generating message contract since element name GetSiteWorkflowAssociationsResult from namespace http://sharePoint.workflow is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sharePoint.workflow/GetSiteWorkflowAssociations", ReplyAction="*")]
        MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsResponse GetSiteWorkflowAssociations(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequest request);
        
        // CODEGEN: Generating message contract since element name workflowName from namespace http://sharePoint.workflow is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sharePoint.workflow/GetSiteWorkflowDetails", ReplyAction="*")]
        MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsResponse GetSiteWorkflowDetails(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name workflow from namespace http://sharePoint.workflow is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://sharePoint.workflow/StartDeclarativeSiteWorkflow", ReplyAction="*")]
        MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowResponse StartDeclarativeSiteWorkflow(MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StartSiteWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartSiteWorkflow", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequestBody Body;
        
        public StartSiteWorkflowRequest() {
        }
        
        public StartSiteWorkflowRequest(MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sharePoint.workflow")]
    internal partial class StartSiteWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string siteUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string workflowName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string eventData;
        
        public StartSiteWorkflowRequestBody() {
        }
        
        public StartSiteWorkflowRequestBody(string siteUrl, string workflowName, string eventData) {
            this.siteUrl = siteUrl;
            this.workflowName = workflowName;
            this.eventData = eventData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StartSiteWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartSiteWorkflowResponse", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowResponseBody Body;
        
        public StartSiteWorkflowResponse() {
        }
        
        public StartSiteWorkflowResponse(MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sharePoint.workflow")]
    internal partial class StartSiteWorkflowResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid StartSiteWorkflowResult;
        
        public StartSiteWorkflowResponseBody() {
        }
        
        public StartSiteWorkflowResponseBody(System.Guid StartSiteWorkflowResult) {
            this.StartSiteWorkflowResult = StartSiteWorkflowResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSiteWorkflowAssociationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteWorkflowAssociations", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequestBody Body;
        
        public GetSiteWorkflowAssociationsRequest() {
        }
        
        public GetSiteWorkflowAssociationsRequest(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class GetSiteWorkflowAssociationsRequestBody {
        
        public GetSiteWorkflowAssociationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSiteWorkflowAssociationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteWorkflowAssociationsResponse", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsResponseBody Body;
        
        public GetSiteWorkflowAssociationsResponse() {
        }
        
        public GetSiteWorkflowAssociationsResponse(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sharePoint.workflow")]
    internal partial class GetSiteWorkflowAssociationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.ArrayOfString GetSiteWorkflowAssociationsResult;
        
        public GetSiteWorkflowAssociationsResponseBody() {
        }
        
        public GetSiteWorkflowAssociationsResponseBody(MDS.WorkflowExtenders.SiteWorkflowService.ArrayOfString GetSiteWorkflowAssociationsResult) {
            this.GetSiteWorkflowAssociationsResult = GetSiteWorkflowAssociationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSiteWorkflowDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteWorkflowDetails", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequestBody Body;
        
        public GetSiteWorkflowDetailsRequest() {
        }
        
        public GetSiteWorkflowDetailsRequest(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sharePoint.workflow")]
    internal partial class GetSiteWorkflowDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string workflowName;
        
        public GetSiteWorkflowDetailsRequestBody() {
        }
        
        public GetSiteWorkflowDetailsRequestBody(string workflowName) {
            this.workflowName = workflowName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class GetSiteWorkflowDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSiteWorkflowDetailsResponse", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsResponseBody Body;
        
        public GetSiteWorkflowDetailsResponse() {
        }
        
        public GetSiteWorkflowDetailsResponse(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sharePoint.workflow")]
    internal partial class GetSiteWorkflowDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowInfo GetSiteWorkflowDetailsResult;
        
        public GetSiteWorkflowDetailsResponseBody() {
        }
        
        public GetSiteWorkflowDetailsResponseBody(MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowInfo GetSiteWorkflowDetailsResult) {
            this.GetSiteWorkflowDetailsResult = GetSiteWorkflowDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StartDeclarativeSiteWorkflowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartDeclarativeSiteWorkflow", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequestBody Body;
        
        public StartDeclarativeSiteWorkflowRequest() {
        }
        
        public StartDeclarativeSiteWorkflowRequest(MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://sharePoint.workflow")]
    internal partial class StartDeclarativeSiteWorkflowRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowInfo workflow;
        
        public StartDeclarativeSiteWorkflowRequestBody() {
        }
        
        public StartDeclarativeSiteWorkflowRequestBody(MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowInfo workflow) {
            this.workflow = workflow;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class StartDeclarativeSiteWorkflowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartDeclarativeSiteWorkflowResponse", Namespace="http://sharePoint.workflow", Order=0)]
        public MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowResponseBody Body;
        
        public StartDeclarativeSiteWorkflowResponse() {
        }
        
        public StartDeclarativeSiteWorkflowResponse(MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class StartDeclarativeSiteWorkflowResponseBody {
        
        public StartDeclarativeSiteWorkflowResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SiteWorkflowActivationServiceSoapChannel : MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SiteWorkflowActivationServiceSoapClient : System.ServiceModel.ClientBase<MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap>, MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap {
        
        public SiteWorkflowActivationServiceSoapClient() {
        }
        
        public SiteWorkflowActivationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiteWorkflowActivationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteWorkflowActivationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiteWorkflowActivationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowResponse MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap.StartSiteWorkflow(MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequest request) {
            return base.Channel.StartSiteWorkflow(request);
        }
        
        public System.Guid StartSiteWorkflow(string siteUrl, string workflowName, string eventData) {
            MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequest inValue = new MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequest();
            inValue.Body = new MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowRequestBody();
            inValue.Body.siteUrl = siteUrl;
            inValue.Body.workflowName = workflowName;
            inValue.Body.eventData = eventData;
            MDS.WorkflowExtenders.SiteWorkflowService.StartSiteWorkflowResponse retVal = ((MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap)(this)).StartSiteWorkflow(inValue);
            return retVal.Body.StartSiteWorkflowResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsResponse MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap.GetSiteWorkflowAssociations(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequest request) {
            return base.Channel.GetSiteWorkflowAssociations(request);
        }
        
        public MDS.WorkflowExtenders.SiteWorkflowService.ArrayOfString GetSiteWorkflowAssociations() {
            MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequest inValue = new MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequest();
            inValue.Body = new MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsRequestBody();
            MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowAssociationsResponse retVal = ((MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap)(this)).GetSiteWorkflowAssociations(inValue);
            return retVal.Body.GetSiteWorkflowAssociationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsResponse MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap.GetSiteWorkflowDetails(MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequest request) {
            return base.Channel.GetSiteWorkflowDetails(request);
        }
        
        public MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowInfo GetSiteWorkflowDetails(string workflowName) {
            MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequest inValue = new MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequest();
            inValue.Body = new MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsRequestBody();
            inValue.Body.workflowName = workflowName;
            MDS.WorkflowExtenders.SiteWorkflowService.GetSiteWorkflowDetailsResponse retVal = ((MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap)(this)).GetSiteWorkflowDetails(inValue);
            return retVal.Body.GetSiteWorkflowDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowResponse MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap.StartDeclarativeSiteWorkflow(MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequest request) {
            return base.Channel.StartDeclarativeSiteWorkflow(request);
        }
        
        public void StartDeclarativeSiteWorkflow(MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowInfo workflow) {
            MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequest inValue = new MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequest();
            inValue.Body = new MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowRequestBody();
            inValue.Body.workflow = workflow;
            MDS.WorkflowExtenders.SiteWorkflowService.StartDeclarativeSiteWorkflowResponse retVal = ((MDS.WorkflowExtenders.SiteWorkflowService.SiteWorkflowActivationServiceSoap)(this)).StartDeclarativeSiteWorkflow(inValue);
        }
    }
}
